// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZyBtD-YxZPrh36qjxD9NQiAA41BpXbs',
    appId: '1:811673093607:web:5d127700cb756305232942',
    messagingSenderId: '811673093607',
    projectId: 'synease-18d6e',
    authDomain: 'synease-18d6e.firebaseapp.com',
    storageBucket: 'synease-18d6e.appspot.com',
    measurementId: 'G-P3Q9NVG6CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVA6pGPbbE0ZuO4TO-JubBfvs32pxvj4',
    appId: '1:811673093607:android:5a440b7150806233232942',
    messagingSenderId: '811673093607',
    projectId: 'synease-18d6e',
    storageBucket: 'synease-18d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLpksOVCc6DXZ6Y9DU0QRIpzzqT9-QPSw',
    appId: '1:811673093607:ios:af9b6e0086a968e0232942',
    messagingSenderId: '811673093607',
    projectId: 'synease-18d6e',
    storageBucket: 'synease-18d6e.appspot.com',
    iosClientId: '811673093607-s6kifhisran1jemhe07un360turvh80a.apps.googleusercontent.com',
    iosBundleId: 'com.example.syndease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLpksOVCc6DXZ6Y9DU0QRIpzzqT9-QPSw',
    appId: '1:811673093607:ios:af9b6e0086a968e0232942',
    messagingSenderId: '811673093607',
    projectId: 'synease-18d6e',
    storageBucket: 'synease-18d6e.appspot.com',
    iosClientId: '811673093607-s6kifhisran1jemhe07un360turvh80a.apps.googleusercontent.com',
    iosBundleId: 'com.example.syndease',
  );
}
